### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by michalhosna**
Adds Symfony + Doctrine.

Local development in Docker + Readme

-----------

This change is [Reviewable](https://reviewable.io/reviews/avcsh/savec/9)

### CODE REVIEW

**Comment by sukovec** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 4 at r1](https://reviewable.io:443/reviews/avcsh/savec/9#-L4YGm2T8az2JoEiKidU:-L4YGm2T8az2JoEiKidV:b-iul7sn) ([raw file](https://github.com/avcsh/savec/blob/f4c4f645f66ac27a0a404e60b7dae705eb42620e/docker-compose.yml#L4)):*
> ```YAML
> services:
>   db:
>     image: postgres:9.6.2
> ```

Why don't use newer version? There's a Pg v10 right now.

PS: Consider this comment primarily as an attempt to try commenting on a line with actually unimportant issue and maybe tell me, that it's not the right way to do it ;) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/9)*

**Comment by vitkabele** [comment]
Reviewed 36 of 36 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/9)*

**Comment by michalhosna** [comment]
Review status: 31 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 4 at r1](https://reviewable.io:443/reviews/avcsh/savec/9#-L4YGm2T8az2JoEiKidU:-L4_Doku1FE8JNWmibLo:b5sfxks) ([raw file](https://github.com/avcsh/savec/blob/f4c4f645f66ac27a0a404e60b7dae705eb42620e/docker-compose.yml#L4)):*
<details><summary><i>Previously, sukovec (Mike S.) wrote…</i></summary><blockquote>

Why don't use newer version? There's a Pg v10 right now.

PS: Consider this comment primarily as an attempt to try commenting on a line with actually unimportant issue and maybe tell me, that it's not the right way to do it ;) 

</blockquote></details>

Actually we probably can use v10. Honestly i just used 9.6 without much of a thinking.

The only reason, i can think of against v10, is if we would like to use AWS RDS, but that's kinda dumb reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/9)*

**Comment by vitkabele** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/9)*

**Pull request merged**
