### PR TITLE
[WIP] ~Initial setup~

### PR DESCRIPTION
**Pull request by michalhosna**
Intial setup.

#3 
#4 
#5

---
This change is [Reviewable](https://reviewable.io/reviews/avcsh/savec/6)

### CODE REVIEW

**Comment by sukovec** [comment]
Reviewed 11 of 16 files at r1, 23 of 23 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 22 at r2](https://reviewable.io:443/reviews/avcsh/savec/6#-L2v1_1rnWt1IN6x1x7k:-L2v1_1syKLs_gwIsh6y:b-vocrnw) ([raw file](https://github.com/avcsh/savec/blob/a6fc9d821c129edb5476996907bbf778c749e302/docker-compose.yml#L22)):*
> ```YAML
>       XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
>       APP_ENV: dev
>       APP_SECRET: 62b197d90141c2d3b55e3cd6920328b0
> ```

Test comment: das ist blbost

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by vitkabele** [comment]
Reviewed 1 of 16 files at r1, 1 of 23 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 22 at r2](https://reviewable.io:443/reviews/avcsh/savec/6#-L2v1_1rnWt1IN6x1x7k:-L2v21vWWllXR5uB3wNT:bb6y6hf) ([raw file](https://github.com/avcsh/savec/blob/a6fc9d821c129edb5476996907bbf778c749e302/docker-compose.yml#L22)):*
<details><summary><i>Previously, sukovec (Mike S.) wrote…</i></summary><blockquote>

Test comment: das ist blbost
</blockquote></details>

Jaja

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by michalhosna** [comment]
Review status: 33 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 22 at r2](https://reviewable.io:443/reviews/avcsh/savec/6#-L2v1_1rnWt1IN6x1x7k:-L2v3QVVhFPZi7llDHTw:b-896fix) ([raw file](https://github.com/avcsh/savec/blob/a6fc9d821c129edb5476996907bbf778c749e302/docker-compose.yml#L22)):*
<details><summary><i>Previously, vitkabele (Vít Kabele) wrote…</i></summary><blockquote>

Jaja
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by sukovec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by vitkabele** [comment]
Reviewed 1 of 16 files at r1, 1 of 23 files at r2, 15 of 15 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by sukovec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.MD, line 21 at r4](https://reviewable.io:443/reviews/avcsh/savec/6#-L3bNU2opebMM2jkSm13:-L3bNR6KR8MRf9qpebeC:bd60fwn) ([raw file](https://github.com/avcsh/savec/blob/cd0f1823ef9ff67b8f91c3df02447d13fdcb3e90/README.MD#L21)):*
> ```
> ```
> - Workdir is set to `/src`, where the current project folder is mounted.
> - creating alias is recomanded `alias svc="docker-compose exec php"`
> ```

s/creating alias is recomanded/creating an alias is recommended/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by sukovec** [comment]
Should I use this strange looking "LGTM" button? Not exactly sure what I'm supposed to do here ;)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6#-:-L3bPJBLZ1LUrFzJOjZL:bpzgxg2)*

**Comment by vitkabele** [comment]
Reviewed 1 of 23 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/avcsh/savec/6)*

**Comment by michalhosna** [comment]
@vitkabele @sukovec Don't review WIP PR, or even WIP commits, those are more backup than final code.

**Comment by michalhosna** [comment]
Closed in favor of #9

**Pull request closed without merging**
